User.create!(name: '平林', age: 34)
User.create!(name: '田中', age: 21)
User.create!(name: '佐藤', age: 32)
User.create!(name: '山岸', age: 33)
User.create!(name: '平', age: 26)
User.create!(name: '加藤', age: 25)
User.create!(name: '鈴木', age: 21)
User.create!(name: '中田', age: 25)
